daviz:
  image: eeacms/daviz:9.8
  ports:
  - "80:8080"
  volumes:
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - data

data:
  image: busybox
  tty: true
  stdin_open: true
  volumes:
  - /opt/zope/var/blobstorage
  - /opt/zope/var/filestorage
  command: ["chown", "-v", "-R", "500:500", "/opt/zope/var"]
